<div id="product_editor" class="fleft pVl pRl pLm">
	<div class="pBxxl">
		<?if ($this->_get('article')->__get('article_id') != NULL):?>
		<h4 class="fc_starfish_gray4 mBs">Introduction</h4>
		<textarea  id="intro" class="pAs expand htmlbox" name="intro"><?=$this->_get('article')->__get('intro')?></textarea>
		
		<h4 class="fc_starfish_gray4 mBs mTxl">Brief	</h4>
		<textarea  id="brief" class="pAs expand htmlbox" name="brief"><?=$this->_get('article')->__get('brief')?></textarea>
		
		<h4 class="fc_starfish_gray4 mBs mTxl">Our Approach	</h4>
		<textarea  id="our_approach" class="pAs expand htmlbox" name="approach"><?=$this->_get('article')->__get('approach')?></textarea>
		
		<h4 class="fc_starfish_gray4 mBs mTxl">What we Did	</h4>
		<textarea  id="what_we_did" class="pAs expand htmlbox" name="what_we_did"><?=$this->_get('article')->__get('what_we_did')?></textarea>
		
		<hr class="pHxl">
		<div id="product_photos" class="fleft posRel">
		<h4 class="fc_starfish_gray4 mBs fleft clearfix">Gallery</h4><br /><br />
		
		<?$i = 1;?>
		<?foreach($this->_get('article_images') as $image):?>
		<!--MAIN IMAGE-->
			<div id="gallery_image_<?=$i?>" class="clearfix posRel mTxl">
				<div class="image_holder fleft mRl">
					<div id="image_overflow">
					   	<div id="img" style="background-image:url(/Data/Images/<?=$image->__get('full_path')?>)"></div>
					</div>
				</div>
	            <span class="show_photo_chooser productPhoto fleft sprite posAbs" id="gallery_image_<?=$i?>"></span>
	            <span class="sprite delete_photo"></span>
				<input class="image_id" type="hidden" name="image_id[]" value="<?=$image->__get('image_id')?>">
				<input class="gallery_image_id" type="hidden" name="gallery_image_id[]" value="<?=$image->__get('article_image_id')?>">
			</div>
			<?$i++;?>
		<?endforeach;?>
			
		<span class="sprite" id="add_photos"></span>
		</div>
		
		<?else:?>
			<div class="fwB fc_starfish_gray3 pointer" id="noImage">No Article to display.</div>
		<?endif;?>
	</div>
</div>

<!-- USED FOR INSTANTIATING A NEW IMAGE -->
<div class="hide image_clone">
	<div class="clearfix mTxl gallery_image posRel">
		<div class="image_holder fleft mRl">
			<div id="image_overflow">
			   	<div id="img"></div>
			</div>
		</div>
	    <span class="show_photo_chooser productPhoto fleft sprite posAbs"></span>
	    <span class="sprite delete_photo"></span>
		<input class="image_id" type="hidden" value="">
		<input class="gallery_image_id" type="hidden" value="0">
	</div>
</div>