<div id="<?=routes::getInstance()->getCurrentTopLevelPageID();?>_content_wrapper">
	<div class="posRel clearfix">
		<span class="backgrounds"<?= $this->displayBackgroundImage(0)?>></span>
			<div class="reservation fright opaqueWrap posAbs">
			</div>
				<div class="noOpacity reservation fleft posAbs">
<!-- 					<p>We are open from 11am to 11pm from Monday to Thursday, Sunday and 11am to 12mn from Friday to Saturday</p> -->
					<p>W Global Center<br />
						30th Street corner 9th Ave.<br />
						Bonifacio Global City,<br />
						Taguig</p><br />
						<h3>Monday to Thursday, Sunday</h3>
						<p>11AM to 11PM</p><br />
						<h3>Friday to Saturday</h3>
						<p>11AM to 12MN</p>
					<hr>
					<div class="clearfix">
						<p>For reservations, please call:</p>
						<br />
						<p>(02) 808 95 17  or  (02) 808 95 03</p>
						<p>reservations@madforgarlic.com.ph</p>
						<div id="openingSoon" class="clearfix">
							<p class="fs-s">OPENING SOON AT</p>
							<i class='fs-b'>Shangri-La Plaza <br />Mall</i>
						</div>
					</div>
				</div>
			<div class="feedback fright opaqueWrap posAbs">
			</div>
				<div class="noOpacity feedback fright posAbs">
					<p class="fs-15">We value your feedback, comments, and suggestions as your outstanding dining experience is our priority. 
	 Kindly fill out the form below:</p>
	 				<hr>
	 				<div class="clearfix">
		 				<form id="contact_form">
		 					<input type="text" name="name" placeholder="Name*">
		 					<input type="text" name="email" placeholder="Email*">
		 					<input type="text" name="contactNumber" placeholder="Contact Number*">
		 					<input type="text" name="branch" placeholder="Branch*" />
		 					<input type="text" name="date_visit" placeholder="Date of Visit*" />
		 					
		 					<textarea name="comment" placeholder="Comment" value = "comment"></textarea>
		 					
		 					<input type="submit" name="submit">
		 					<p>* required fields</p>
		 				</form>
		 				<div id="sent-confirmation">
							<h2>Thank You!</h2>
							<br>
							Your message has been sent.
						</div>
					</div>
	 			</div>
	 			
	</div>
</div>