<div id="<?=routes::getInstance()->getCurrentTopLevelPageID();?>_content_wrapper">
	<div class="posRel clearfix">
		<span class="backgrounds"<?= $this->displayBackgroundImage(0)?>></span>
			<div class="reservation fright opaqueWrap posAbs">
			</div>
				<div class="noOpacity reservation fleft posAbs">
					<p>We are open from 11am to 11pm from Monday to Thursday, Sunday and 11am to 12mn from Friday to Saturday</p>
					<hr>
					<div class="clearfix">
						<p>For reservations, please call:</p>
						<p class="fs-23">Joie Arvesu</p>
						<p class="fs-9">SENIOR OPERATIONS DIRECTOR</p>
						<p>(02) 808 95 17  or  (02) 808 95 03</p>
					</div>
				</div>
			<div class="feedback fright opaqueWrap posAbs">
			</div>
				<div class="noOpacity feedback fright posAbs">
					<p class="fs-15">We value your feedback, comments, and suggestions as your outstanding dining experience is our priority. 
	 Kindly fill out the form below:</p>
	 				<hr>
	 				<div class="clearfix">
		 				<form id="contact_form">
		 					<input type="text" name="name" placeholder="Name*">
		 					<input type="text" name="email" placeholder="Email*">
		 					<textarea name="comment" placeholder="Comment" value = "comment"></textarea>
		 					<input type="submit" name="submit">
		 				</form>
		 				<div id="sent-confirmation">
							<h2>Thank You!</h2>
							<br>
							Your message has been sent.
						</div>
					</div>
	 			</div>
	 			
	</div>
</div>