<div id="<?=routes::getInstance()->getCurrentTopLevelPageID();?>_content_wrapper" class="clearfix">
	<div class="posRel clearfix">
		<span class="backgrounds"<?= $this->displayBackgroundImage(0)?>></span>
			<div class="globalContainer opaqueWrap fright posAbs">
			</div>
			<div class="globalContainer noOpacity fright posAbs">
				<?= $this->displayElement('page_content_editor')?>
			</div>
	</div>
</div>