<div id="footer" class="pVl clearfix">
	<div id="socialPlug" class="fleft">
		<a href="https://www.facebook.com/MadForGarlicPhilippines" id="facebook" target="blank">facebook</a>
		<a href="https://twitter.com/madforgarlicph" id="twitter" target="blank">twitter</a>
	</div>
	<div id="forReserve" class="fleft clearfix">
		<p class="fs-xs">For reservations, please call</p>
		<p class="fs-s">(02) 808 95 17 and (02) 808 95 03</p>
		<span id="sunLogo"></span>
		<p>COPYRIGHT (C) SUNATFOOD. ALL RIGHTS RESERVED</p>
	</div>
	<div id="newsletter" class="fright clearfix">
		<p>subscribe to our newsletters</p>
	<form>
		<input type="text" placeholder="email">
		<input type="submit" value="submit">
	</form>
	</div>
</div>