<!-- <h1><img src="/Project/Design/1_Website/Pages/primary/portfolio/images/all-thing-bright-and--beautiful.png" alt="Just some of our recent works" width="727" height="123" /></h1>
	
	
	<?foreach($this->_get('array_of_articles') as $article):?>
	
 	<div class="project_container pVm clearfix">
		<div class="fleft"><span class="project_image" style="background-image:url('/Project/Design/1_Website/Pages/primary/portfolio/images/project_image.png');"></span></div>
 		<div class="fright">
			<h3><a href="/our-portfolio/<?=$article->__get('permalink'); ?>" class="fs-m1"><?=$article->__get('article_title');?></a></h3>
			<p><?=$article->__get('intro');?></p>
			<a class="link_button" href="<?=$article->__get('link_url');?>" target="_blank"><?=$article->__get('link_url');?></a>
		</div> 
	</div> 
	<?endforeach;?>-->