<div id="leftColumn" class="fleft"> 
	<div class="pTl pLl pRl" id="heading">
		<div class="pAl">
			<h3>FILTER</h3>
		</div>
		<div class="clearfix mLl" id="sideNavigation">
			<form method="POST" action="/subscriber/subscriber/filter" style="color:black">
				<label>Email</label>
				<input type="text" name="email" /><br>
			<input class="sprite2 mAl"type="submit" name="filter" />
		</form>
		</div>
	</div>
</div> 